services:
  - type: web
    name: pdf-encryptator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y qpdf
      pip install --no-cache-dir -r ./requirements.txt
    startCommand: gunicorn app:app